import SwiftUI

struct StepDetailView: View {
    let step: PipelineStep
    let pipelineID: UUID
    @EnvironmentObject var vm: AppViewModel
    @ObservedObject private var profileManager = CLIProfileManager.shared

    @State private var name: String = ""
    @State private var selectedTool: ToolType = .codex
    @State private var modelOverride: String = ""
    @State private var command: String = ""
    @State private var prompt: String = ""
    @State private var dependsOnStepIDs: [UUID] = []
    @State private var continueOnFailure: Bool = false
    @State private var showAdvanced = false
    @State private var savedStepSnapshot: PipelineStep?

    var body: some View {
        Form {
            if vm.isPipelineExecuting(pipelineID) {
                Section {
                    Label(L10n.text("step.lockedWhileRunning", fallback: "This pipeline is running. Stage and step configuration can't be edited right now."), systemImage: "lock.fill")
                        .font(.caption)
                        .foregroundStyle(.orange)
                }
            }

            Section {
                TextField(L10n.text("common.name", fallback: "Name"), text: $name)
                    .textFieldStyle(.roundedBorder)
                    .disabled(isEditingLocked)

                HStack {
                    Text(L10n.text("common.tool", fallback: "Tool"))
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Picker("", selection: $selectedTool) {
                        ForEach(ToolType.allCases) { tool in
                            Label(tool.displayName, systemImage: tool.iconName).tag(tool)
                        }
                    }
                    .pickerStyle(.menu)
                    .frame(maxWidth: 140)
                    .disabled(isEditingLocked)
                }

                HStack {
                    Text(L10n.text("common.model", fallback: "Model"))
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    TextField(L10n.text("common.leaveEmptyForDefault", fallback: "Leave empty for default"), text: $modelOverride)
                        .textFieldStyle(.roundedBorder)
                        .frame(maxWidth: 200)
                        .disabled(isEditingLocked)
                }

                Toggle(L10n.text("step.continueOnFailure", fallback: "Continue on failure"), isOn: $continueOnFailure)
                    .disabled(isEditingLocked)

                effectiveCommandPreview
            } header: {
                HStack(spacing: 8) {
                    Text(L10n.text("common.configuration", fallback: "Configuration"))
                    Spacer()
                    if isDirty {
                        Text(L10n.text("common.unsavedChanges", fallback: "Unsaved changes"))
                            .font(.caption)
                            .foregroundStyle(.orange)
                    }
                    Button(L10n.text("common.saveChanges", fallback: "Save Changes")) {
                        applyChanges()
                    }
                    .buttonStyle(.borderedProminent)
                    .controlSize(.small)
                    .disabled(!isDirty || isEditingLocked)
                }
                .textCase(nil)
            }

            DisclosureGroup(L10n.text("common.advanced", fallback: "Advanced"), isExpanded: $showAdvanced) {
                VStack(alignment: .leading, spacing: 6) {
                    Text(L10n.text("step.customCommandOverride", fallback: "Custom Command Override"))
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    ZStack(alignment: .topLeading) {
                        if command.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                            Text(L10n.text("step.leaveEmptyAutoGenerated", fallback: "Leave empty to use auto-generated command"))
                                .font(.system(.body, design: .monospaced))
                                .foregroundStyle(.tertiary)
                                .padding(.horizontal, 8)
                                .padding(.vertical, 10)
                                .allowsHitTesting(false)
                        }

                        TextEditor(text: $command)
                            .font(.system(.body, design: .monospaced))
                            .frame(minHeight: 60)
                            .scrollContentBackground(.hidden)
                            .disabled(isEditingLocked)
                    }
                    .padding(2)
                    .background(.background, in: RoundedRectangle(cornerRadius: 8))
                    .overlay(
                        RoundedRectangle(cornerRadius: 8)
                            .stroke(.quaternary, lineWidth: 1)
                    )

                    Text(L10n.text("step.promptPlaceholderHint", fallback: "Use `{{prompt}}` to inline the prompt. If empty, command is generated from Tool + Model + Environment."))
                        .font(.caption2)
                        .foregroundStyle(.secondary)

                    if !command.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                        Button(L10n.text("step.clearCustomCommand", fallback: "Clear Custom Command")) {
                            command = ""
                        }
                        .font(.caption)
                        .foregroundStyle(.red)
                    }
                }
            }

            Section(L10n.text("common.prompt", fallback: "Prompt")) {
                TextEditor(text: $prompt)
                    .font(.system(.body, design: .monospaced))
                    .frame(minHeight: 120)
                    .disabled(isEditingLocked)
            }

            Section(L10n.text("step.runAfter", fallback: "Run After")) {
                let allSteps = vm.selectedPipeline?.allSteps.filter { $0.id != step.id } ?? []
                if allSteps.isEmpty {
                    Text(L10n.text("step.runAfterNoDependencies", fallback: "This step can run immediately. No other steps are available in this pipeline."))
                        .font(.caption)
                        .foregroundStyle(.secondary)
                } else {
                    Text(L10n.text("step.runAfterHint", fallback: "Select the steps that must finish before this step can run."))
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    ForEach(allSteps) { other in
                        let isDependent = dependsOnStepIDs.contains(other.id)
                        HStack {
                            Image(systemName: isDependent ? "checkmark.circle.fill" : "circle")
                                .foregroundStyle(isDependent ? .blue : .secondary)
                            Text(other.name)
                        }
                        .contentShape(Rectangle())
                        .onTapGesture { toggleDependency(other.id) }
                    }
                }
            }
            .disabled(isEditingLocked)
        }
        .formStyle(.grouped)
        .navigationTitle(L10n.text("step.detail", fallback: "Step Detail"))
        .onAppear { loadFromStep() }
        .onChange(of: step) { _, _ in
            loadFromStep()
        }
        .onChange(of: vm.isPipelineExecuting(pipelineID)) { _, isRunning in
            if !isRunning && isDirty {
                scheduleApplyChanges()
            }
        }
        .onDisappear {
            if isDirty && !vm.isPipelineExecuting(pipelineID) {
                scheduleApplyChanges()
            }
        }
    }

    // MARK: - Effective Command Preview

    @State private var showCopied = false

    @ViewBuilder
    private var effectiveCommandPreview: some View {
        let profile = profileManager.activeProfile
        let preview = resolvedEffectiveCommand(profile: profile)
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text(L10n.text("step.resolvedCommand", fallback: "Resolved Command"))
                    .font(.caption)
                    .foregroundStyle(.secondary)
                Spacer()
                Button {
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(preview, forType: .string)
                    showCopied = true
                    DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
                        showCopied = false
                    }
                } label: {
                    Label(showCopied ? L10n.text("common.copied", fallback: "Copied") : L10n.text("common.copy", fallback: "Copy"), systemImage: showCopied ? "checkmark" : "doc.on.doc")
                        .font(.caption2)
                }
                .buttonStyle(.borderless)
                .foregroundStyle(showCopied ? .green : .secondary)
            }
            Text(preview)
                .font(.system(.caption, design: .monospaced))
                .foregroundStyle(.secondary)
                .textSelection(.enabled)
                .lineLimit(2)
        }
    }

    // MARK: - Helpers

    private func resolvedEffectiveCommand(profile: CLIProfile) -> String {
        let trimmedCommand = command.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedCommand.isEmpty {
            return trimmedCommand
        }
        let model = modelOverride.trimmingCharacters(in: .whitespacesAndNewlines)
        return selectedTool.defaultCommandTemplate(
            model: model.isEmpty ? nil : model,
            profile: profile
        )
    }

    private func loadFromStep() {
        savedStepSnapshot = step
        name = step.name
        selectedTool = step.tool
        modelOverride = step.model ?? ""
        command = step.command ?? ""
        prompt = step.prompt
        dependsOnStepIDs = step.dependsOnStepIDs
        continueOnFailure = step.continueOnFailure
        showAdvanced = step.hasCustomCommand
    }

    private func applyChanges() {
        guard !vm.isPipelineExecuting(pipelineID) else { return }
        var updated = step
        updated.name = name
        updated.tool = selectedTool
        let trimmedModel = modelOverride.trimmingCharacters(in: .whitespacesAndNewlines)
        updated.model = trimmedModel.isEmpty ? nil : trimmedModel
        updated.command = sanitizedCommand(command)
        updated.prompt = prompt
        updated.dependsOnStepIDs = dependsOnStepIDs
        updated.continueOnFailure = continueOnFailure
        vm.updateStep(updated, in: pipelineID)
        savedStepSnapshot = updated
    }

    private func toggleDependency(_ otherID: UUID) {
        if let idx = dependsOnStepIDs.firstIndex(of: otherID) {
            dependsOnStepIDs.remove(at: idx)
        } else {
            dependsOnStepIDs.append(otherID)
        }
    }

    private func sanitizedCommand(_ command: String) -> String? {
        let trimmed = command.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        return trimmed
            .replacingOccurrences(of: "\"{{prompt}}\"", with: "{{prompt}}")
            .replacingOccurrences(of: "'{{prompt}}'", with: "{{prompt}}")
    }

    private var isDirty: Bool {
        let baseline = savedStepSnapshot ?? step
        let trimmedCommand = sanitizedCommand(command)
        let trimmedSavedCommand = baseline.command.flatMap { sanitizedCommand($0) }
        let trimmedModel = modelOverride.trimmingCharacters(in: .whitespacesAndNewlines)
        let savedModel = baseline.model ?? ""

        return name != baseline.name
            || selectedTool != baseline.tool
            || trimmedModel != savedModel
            || prompt != baseline.prompt
            || continueOnFailure != baseline.continueOnFailure
            || trimmedCommand != trimmedSavedCommand
            || Set(dependsOnStepIDs) != Set(baseline.dependsOnStepIDs)
    }

    private func scheduleApplyChanges() {
        DispatchQueue.main.async {
            applyChanges()
        }
    }

    private var isEditingLocked: Bool {
        vm.isPipelineExecuting(pipelineID)
    }
}
